// <auto-generated />
namespace ALPPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class attBanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(attBanco));
        
        string IMigrationMetadata.Id
        {
            get { return "201903281702204_attBanco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
